import = [
    # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    "~/.config/alacritty/themes/themes/gruvbox_material.toml"
]

[font]
size = 18

[font.normal]
family = "NotoMono Nerd Font"

[window]
decorations = "Full"
startup_mode = "Maximized"
opacity = 0.9
